services:
  siren:
    image: sigp/siren
    ports:
      - "4443:443" # comment this line when using `SSL_ENABLED=false`
#      - "4080:80"  # uncomment this line when using `SSL_ENABLED=false`
    env_file:
      - .env
