services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    networks:
      - internet
      - no_internet
    ports:
      - "4080:4080"  # For Siren web interface
      - "4443:443"   # For Siren web interface with SSL
    volumes:
      - ./docker-assets/nginx_proxy.conf.template:/etc/nginx/nginx.conf.template:ro
    command: /bin/bash -c "export BN_TARGET=$(echo $BEACON_URL | awk -F'[/:]' '{print $4 \":\" $5}') && export VC_TARGET=$(echo $VALIDATOR_URL | awk -F'[/:]' '{print $4 \":\" $5}') && envsubst '$$BN_TARGET $$VC_TARGET $$SIREN_HOST' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    env_file:
      - .env


    restart: unless-stopped     # Don't restart if manually stopped

  siren:
    container_name: siren
    image: sigp/siren
    networks:
      - no_internet           # Only on internal network
    expose:
      - "80"
    env_file:
      - .env
    tmpfs:
      - /tmp:noexec,nosuid    # Mount tmp with restricted permissions
      - /run:noexec,nosuid    # Required for nginx pid file
    environment:
      - NODE_ENV=production
      - BEACON_URL=http://nginx-proxy:9001
      - VALIDATOR_URL=http://nginx-proxy:9002
      - SSL_ENABLED=false
      - PORT=3000
      - BACKEND_URL=http://127.0.0.1:3001
    # Security enhancements
    security_opt:
      - no-new-privileges:true  # Prevent privilege escalation
    
    healthcheck:             # Add health monitoring
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped  # Don't restart if manually stopped

networks:
  internet:
    name: internet
    driver: bridge
  no_internet:
    name: no_internet
    driver: bridge
    internal: true          # Prevents direct internet access
    # # Enable network encryption
    driver_opts:
      encrypted: "true"
