version: '3.7'
services:
  whoami:
    image: traefik/whoami
    networks:
      - caddy
    labels:
      caddy: whoami.sigp1.com
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true